### ISSUE TITLE
Mailing list not open to the public?

### ISSUE THREAD

**Issue by eedrummer** [data61/anonlink#219]
When attempting to follow the link to the mailing list that is provided in the README, I get the following error message in my browser:

    You do not have permission to access this content. (#418)

**Comment by hardbyte** [comment]
Sorry - I tried to lock down the list access control but obviously took it too far. Should be visible again!

Please reopen if it isn't fixed.

**Comment by eedrummer** [comment]
Thanks! I can get in now.
