### ISSUE TITLE
Wheels not published for each platform

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink#229]
Travis builds wheel files using the manylinux docker image. See an [upstream example](https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh) and [ours](https://github.com/data61/anonlink/blob/master/travis/build-dist.sh).

This issue is to build and publish a wheel file for different platforms (and architectures?)

**Comment by hardbyte** [comment]
For reference this is what numpy uploads to pypi:
```
numpy-1.17.1-cp35-cp35m-macosx_10_9_x86_64.whl
numpy-1.17.1-cp35-cp35m-manylinux1_i686.whl
numpy-1.17.1-cp35-cp35m-manylinux1_x86_64.whl
numpy-1.17.1-cp35-cp35m-win32.whl
numpy-1.17.1-cp35-cp35m-win_amd64.whl
numpy-1.17.1-cp36-cp36m-macosx_10_9_x86_64.whl
numpy-1.17.1-cp36-cp36m-manylinux1_i686.whl
numpy-1.17.1-cp36-cp36m-manylinux1_x86_64.whl
numpy-1.17.1-cp36-cp36m-win32.whl
numpy-1.17.1-cp36-cp36m-win_amd64.whl
numpy-1.17.1-cp37-cp37m-macosx_10_9_x86_64.whl
numpy-1.17.1-cp37-cp37m-manylinux1_i686.whl
numpy-1.17.1-cp37-cp37m-manylinux1_x86_64.whl
numpy-1.17.1-cp37-cp37m-win32.whl
numpy-1.17.1-cp37-cp37m-win_amd64.whl
numpy-1.17.1.zip
```

**Comment by hardbyte** [comment]
This could help? https://github.com/joerick/cibuildwheel

**Comment by hardbyte** [comment]
Needs to be automatically published to pypi e.g. the macos binary wheel

**Comment by wilko77** [comment]
with release 0.13.0 we publish wheels for Linux, Mac, Windows for Python 3.6, 3.7, 3.8.
That should be enough for now.
