### ISSUE TITLE
Use pypi version of cibuildwheel once macos support for binary wheels is fixed

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink#242]
We are using a [fork of cibuildwheel](https://github.com/Czaki/cibuildwheel) which gives us working macos c++11 support.

This seems to be tracked in the main repo here https://github.com/joerick/cibuildwheel/pull/156

This issue is for us to move back to the pypi version of cibuildwheel once macos support for binary wheels with c++11 works again.

**Comment by Czaki** [comment]
I select another way than using Python 10.9.   Read changes in pull request.

**Comment by Czaki** [comment]
Another update. You need to specify MACOSX_DEPLOYMENT_TARGET variable with value 10.9.

**Comment by hardbyte** [comment]
Thanks @Czaki

**Comment by Czaki** [comment]
New release of wheel is released. Changes from joerick/cibuildwheel#156 are merged.

**Comment by hardbyte** [comment]
Thanks @Czaki! I've tried this out in PR #257 which is a step in the right direction but since our C/C++ code **doesn't** support 32 bit arch we will have to wait for https://github.com/joerick/cibuildwheel/pull/220 as well

**Comment by wilko77** [comment]
addressed in #302
