### ISSUE TITLE
Remove dependency on clkhash

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink#52]
Currently a few e2e tests rely on clkhash for generating the bloomfilters.

While it is nice to do an integration test between the related libraries we shouldn't introduce a clkhash as a dependency just for the integration test.

They are also used in the benchmarking script, comment from @wilko77:
> none of the benchmarks actually needs real CLKs, as all you measure is timing. You could easily fake CLKs by choosing them randomly. This would not require a clkhash dependency.

**Comment by mhsiah** [comment]
It's not quite as simple as @wilko77 suggests: the performance on randomly generated CLKs will be very different to performance on typical data (see sdc.pdf file shared in #linking on 29/1/2018).

**Comment by hardbyte** [comment]
`clkhash` is listed as a test dependency
