### ISSUE TITLE
anonlink.benchmark documentation clarity 

### ISSUE THREAD

**Issue by emmcauley** [data61/anonlink#530]
It's not entirely clear how to integrate the environmental flags into anonlink.benchmark. The README says: 

"To enable slightly larger tests add the following environment variables:

INCLUDE_10K
INCLUDE_100K"

but it's not clear what to set this to (`export INCLUDE_10k = 1` did not work) or what I should look for in the resulting table (I assume an uptick in size 1, 2, and number of comparisons). 

If you can provide more clarification I'm happy to open a PR to update the documentation. Thanks!

**Comment by gusmith** [comment]
Hi,

I just had a brief look, but the environment variables `INCLUDE_10K` and `INCLUDE_100K` are to run longer unit tests. They are not related to the benchmark (note also that they are upper case, thus `export INCLUDE_10k = 1` would not work, the "k" you wrote is lower case). 

To validate this, you can run
```
$ pytest tests/test_e2e.py 
============================= test session starts ==============================
[...]
collected 10 items                                                             

tests/test_e2e.py ....ss....                                             [100%]

========================= 8 passed, 2 skipped in 1.49s =========================
```

and when you set the env var:
```
$ INCLUDE_10K=1 pytest tests/test_e2e.py 
============================= test session starts ==============================
platform darwin -- Python 3.9.10, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/s120573/ambiata/data61/anonlink
plugins: hypothesis-6.9.2, cov-3.0.0
collected 10 items                                                             

tests/test_e2e.py .....s....                                             [100%]

========================= 9 passed, 1 skipped in 8.94s =========================
```

See how by setting the env var, one extra test is ran (not skipped).

For the benchmark, if you would like to run it on bigger datasets, you will have to update the code directly. 
If you feel like it, I'm sure the owner of the repo would be happy if you make the base test size configurable. It is currently set to 4000 https://github.com/data61/anonlink/blob/main/anonlink/benchmark.py#L118.
I would also recommend looking at the method https://github.com/data61/anonlink/blob/main/anonlink/benchmark.py#L75 to understand what the benchmark runs.

**Comment by emmcauley** [comment]
Ah, ok, thanks for the context @gusmith!
