### ISSUE TITLE
Accelerated API for processing n x m entities

### ISSUE THREAD

**Issue by unzvfu** [data61/anonlink#67]
This issue partly supersedes #29 where Brian says:

> At the moment in `entitymatch.cffi_filter_similarity_k` we pass in two lists of bloom filters, but we end up calling the native code `n` times. This issue is to move that iteration into the C library.

Aha! Link: https://csiro.aha.io/features/ANONLINK-67

**Comment by hardbyte** [comment]
This was done as part of the move to use cython instead of cffi. See [`dice_many_to_many`](https://github.com/hardbyte/anonlink/blob/828fbf5c78c63d8dbf32c2537a25cd9cad9ba538/anonlink/similarities/_dice.pyx#L118-L177)
